env:
  global:
os: linux
dist: trusty
sudo: required
language: cpp
compiler:
- gcc
before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get update -qq
- sudo apt-get install -y cmake
- cmake --version
- sudo apt-get install -y --force-yes openscenegraph=3.4
#- sudo apt-get install -y libopenscenegraph-dev
- osgversion
script:
- cmake -DCMAKE_BUILD_TYPE=Release . && make
notifications:
  email:
    recipients:
    - leadcoder@gmail.com
addons:
  coverity_scan:
    project:
      name: "leadcoder/osgVegetation"
      description: "osgVegetation"
    notification_email: leadcoder@gmail.com.com
    build_command_prepend: cmake -DCMAKE_BUILD_TYPE=Release
    build_command: make -j3
